### PR TITLE
Be able to check the file and all the parents

### PR DESCRIPTION
**Pull request by sbrunner**

### CODE REVIEW

**Comment by zb3** [comment]
Thx, I'll merge this, however that line 225 in test file looks duplicated (or I can't see...)

**Comment by sbrunner** [comment]
I just want to test in booth case with is_directory True/False, but I miss it, => just added :-)

**Comment by zb3** [comment]
Oops it says I can't merge this automatically - conflicts :(
Did I screw up by merging #5 first? But I suspect this is caused by the `unittest.main()` line

**Comment by sbrunner** [comment]
Just done, many thanks :-)

**Comment by zb3** [comment]
Merged!

**Comment by sbrunner** [comment]
Thanks, is it possible to upload a new package on pypi?

**Comment by zb3** [comment]
I think I did it now: https://pypi.python.org/pypi/zgitignore/0.8.0
I'll try to update readme later if I don't forget :)

**Comment by sbrunner** [comment]
Many thanks :-)

**Pull request merged**
